USE [master]
GO
/****** Object:  Database [AeroSpectroDB4]    Script Date: 28.05.2025 9:15:26 ******/
CREATE DATABASE [AeroSpectroDB4]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AeroSpectroDB4', FILENAME = N'G:\sql\MSSQL16.QWE\MSSQL\DATA\AeroSpectroDB4.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AeroSpectroDB4_log', FILENAME = N'G:\sql\MSSQL16.QWE\MSSQL\DATA\AeroSpectroDB4_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [AeroSpectroDB4] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AeroSpectroDB4].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AeroSpectroDB4] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET ARITHABORT OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AeroSpectroDB4] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AeroSpectroDB4] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET  ENABLE_BROKER 
GO
ALTER DATABASE [AeroSpectroDB4] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AeroSpectroDB4] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET RECOVERY FULL 
GO
ALTER DATABASE [AeroSpectroDB4] SET  MULTI_USER 
GO
ALTER DATABASE [AeroSpectroDB4] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AeroSpectroDB4] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AeroSpectroDB4] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AeroSpectroDB4] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AeroSpectroDB4] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AeroSpectroDB4] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'AeroSpectroDB4', N'ON'
GO
ALTER DATABASE [AeroSpectroDB4] SET QUERY_STORE = ON
GO
ALTER DATABASE [AeroSpectroDB4] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [AeroSpectroDB4]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 28.05.2025 9:15:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Areas]    Script Date: 28.05.2025 9:15:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Areas](
	[AreaID] [int] IDENTITY(1,1) NOT NULL,
	[ProjectID] [int] NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[Coordinates] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[AreaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Clients]    Script Date: 28.05.2025 9:15:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clients](
	[ClientID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[ContactInfo] [nvarchar](255) NULL,
	[UserID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ClientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Measurements]    Script Date: 28.05.2025 9:15:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Measurements](
	[MeasurementID] [int] IDENTITY(1,1) NOT NULL,
	[ProfileID] [int] NOT NULL,
	[Timestamp] [datetime] NOT NULL,
	[Latitude] [float] NOT NULL,
	[Longitude] [float] NOT NULL,
	[GammaValue] [float] NOT NULL,
	[Altitude] [float] NOT NULL,
	[SpectrumData] [nvarchar](max) NULL,
	[SpectrumChannels] [int] NOT NULL,
	[SpectrumEnergyMin] [float] NOT NULL,
	[SpectrumEnergyMax] [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MeasurementID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Profiles]    Script Date: 28.05.2025 9:15:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Profiles](
	[ProfileID] [int] IDENTITY(1,1) NOT NULL,
	[AreaID] [int] NULL,
	[Name] [nvarchar](255) NOT NULL,
	[Type] [nvarchar](100) NULL,
	[StartCoordinates] [nvarchar](255) NULL,
	[EndCoordinates] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ProfileID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProjectProfiles]    Script Date: 28.05.2025 9:15:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProjectProfiles](
	[ProjectID] [int] NOT NULL,
	[ProfileID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ProjectID] ASC,
	[ProfileID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Projects]    Script Date: 28.05.2025 9:15:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Projects](
	[ProjectID] [int] IDENTITY(1,1) NOT NULL,
	[ClientID] [int] NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[ContractNumber] [nvarchar](100) NULL,
	[StartDate] [date] NOT NULL,
	[EndDate] [date] NOT NULL,
	[Description] [nvarchar](max) NULL,
	[CreatedByUserID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ProjectID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 28.05.2025 9:15:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](255) NOT NULL,
	[PasswordHash] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_Users_Username] UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_Clients_UserID]    Script Date: 28.05.2025 9:15:27 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Clients_UserID] ON [dbo].[Clients]
(
	[UserID] ASC
)
WHERE ([UserID] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Measurements] ADD  DEFAULT ((0)) FOR [SpectrumChannels]
GO
ALTER TABLE [dbo].[Measurements] ADD  DEFAULT ((0)) FOR [SpectrumEnergyMin]
GO
ALTER TABLE [dbo].[Measurements] ADD  DEFAULT ((0)) FOR [SpectrumEnergyMax]
GO
ALTER TABLE [dbo].[Areas]  WITH CHECK ADD FOREIGN KEY([ProjectID])
REFERENCES [dbo].[Projects] ([ProjectID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Clients]  WITH CHECK ADD  CONSTRAINT [FK_Clients_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Clients] CHECK CONSTRAINT [FK_Clients_Users]
GO
ALTER TABLE [dbo].[Measurements]  WITH CHECK ADD FOREIGN KEY([ProfileID])
REFERENCES [dbo].[Profiles] ([ProfileID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Profiles]  WITH CHECK ADD FOREIGN KEY([AreaID])
REFERENCES [dbo].[Areas] ([AreaID])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[ProjectProfiles]  WITH CHECK ADD FOREIGN KEY([ProfileID])
REFERENCES [dbo].[Profiles] ([ProfileID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ProjectProfiles]  WITH CHECK ADD FOREIGN KEY([ProjectID])
REFERENCES [dbo].[Projects] ([ProjectID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Projects]  WITH CHECK ADD FOREIGN KEY([ClientID])
REFERENCES [dbo].[Clients] ([ClientID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Projects]  WITH CHECK ADD  CONSTRAINT [FK_Projects_Users] FOREIGN KEY([CreatedByUserID])
REFERENCES [dbo].[Users] ([UserID])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Projects] CHECK CONSTRAINT [FK_Projects_Users]
GO
USE [master]
GO
ALTER DATABASE [AeroSpectroDB4] SET  READ_WRITE 
GO
